### ISSUE TITLE
Ligatures for !==, ===, and =>

### ISSUE THREAD

**Issue by appsforartists** [alexeiva/Inconsolata#17]
There are three ligatures that are useful for JS development that I'd love to see in Inconsolata.  I've started implementing them (and will be testing them locally).

<img width="273" alt="screen shot 2018-02-26 at 10 51 14 am" src="https://user-images.githubusercontent.com/926648/36700458-9e34287e-1b04-11e8-9826-445aff81f25a.png">

Would you accept a PR that included them?

**Comment by sleepiejohn** [comment]
I know little about font design, but wouldn't be easier to use FiraCode's ligatures and patch it on Inconsolata ?

**Comment by appsforartists** [comment]
But why?  Inconsolata is its own font.  Having its own ligatures feels better both for the font and for the programming font ecosystem than frankensteining-on somebody else's glyphs.

**Comment by appsforartists** [comment]
Thanks.

Personally, I'm only interested in adding ligatures for JavaScript.  (Of course, other designers are welcome to submit their own ligatures too.)  I actually like that we're only adding triple equals (rather than both double and triple, as in Fira) because it makes it obvious when you've forgotten the third one.

**Comment by alexeiva** [comment]
@appsforartists you are welcome to PR. Here are [Build Instructions ][build]

@raphlinus mentioned on d-ligatures in this [discussion](https://groups.google.com/d/msg/googlefonts-discuss/wgVuOx9yo5k/snSXATRhDAAJ):

> When doing "programmer ligatures", I think it's important that the ligature doesn't affect the metrics. So if you're making a "->" ligature, it needs to be a long arrow, twice the normal width. (on second reading, this might not be an issue in what you've actually done, but just throwing it out there).



[build]: https://github.com/cyrealtype/Inconsolata#inconsolata-build-instructions

**Comment by appsforartists** [comment]
Glad to hear it!  I'll open one.  😃

**Comment by alexeiva** [comment]
We can make this feature default and include a patch script that removes dligs for users that do not need it. There is a similar script [here](https://github.com/alexeiva/jura/blob/master/sources/patch_dotted_zero.py):

**Comment by alexeiva** [comment]
@appsforartists The widths of ligatures are fine: double or triple the normal size.

I fixed a few things:
* updated version number
* copied ligs to Bold to prevent ligatures from breaking during style swapping
* regenerated both styles

Here is [v.2.010 release](https://github.com/alexeiva/Inconsolata/releases/tag/v2.010)
